// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'loginApi_test.dart' as loginApi_test;
import 'login_feilds_validator_test.dart'as login_validator;

void main() {
  loginApi_test.main();
  login_validator.main();
}
