name: Seller_App
description: A Mobile application for seller
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  firebase_messaging: ^7.0.2
  shared_preferences: ^2.0.5
  animated_check: ^1.0.0
  intl: ^0.17.0
  circular_countdown_timer:
  
  
  flutter:  
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  cached_network_image: ^3.0.0
  shimmer: ^2.0.0
  flutter_switch: ^0.3.0
  provider: ^5.0.0
  pin_code_fields:   

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
 
  assets:
    - assets/
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  
