name: Seller_App
description: A Mobile application for seller
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  firebase_messaging: ^7.0.3
  firebase_core:
  shared_preferences: ^2.0.5
  animated_check: ^1.0.0
  fluentui_system_icons: ^1.1.120
  google_fonts: ^2.0.0
  percent_indicator: "^2.1.7+2"
  intl: ^0.17.0
  custom_timer: ^0.0.3
  slide_countdown_clock: ^1.0.3
  
  
  flutter:  
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  cached_network_image: ^3.0.0
  shimmer: ^2.0.0
  flutter_switch: ^0.3.0
  provider: ^5.0.0
  fluttertoast: ^3.1.3
  flutter_countdown_timer: ^4.1.0
  countdown_flutter: ^0.1.2
  avatar_glow: ^1.1.0
  stop_watch_timer: ^1.1.0+1
  pin_code_fields:   

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
 
  assets:
    - assets/Images/
 
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/Fonts/Raleway-Regular.ttf
        - asset: assets/Fonts/Raleway-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  
